# Generated by Django 5.0.6 on 2024-12-15 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=2048)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("read", models.BooleanField(default=False)),
                ("conversation_id", models.CharField(db_index=True, max_length=255)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["conversation_id", "timestamp"],
                        name="conversation_timestamp_idx",
                    ),
                    models.Index(
                        fields=["sender", "read", "timestamp"],
                        name="sender_read_timestamp_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                check=models.Q(("sender", models.F("receiver")), _negated=True),
                name="different_sender_receiver_constraint",
                violation_error_message="Sender and receiver must be different users",
            ),
        ),
    ]
