# Generated by Django 5.0.6 on 2024-12-13 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="message",
            name="sender_receiver_different",
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                check=models.Q(("sender", models.F("receiver")), _negated=True),
                name="different_sender_receiver_constraint",
                violation_error_message="Sender and receiver must be different users",
            ),
        ),
    ]
