# Generated by Django 5.0.6 on 2024-12-15 08:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["receiver", "sender", "read"],
                name="messenger_m_receive_bd58e4_idx",
            ),
        ),
    ]
