# Generated by Django 5.1.5 on 2026-02-20 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0002_message_messenger_m_receive_bd58e4_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "conversation_id"],
                include=("id",),
                name="sender_conv_covering_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["receiver", "conversation_id"],
                include=("id",),
                name="receiver_conv_covering_idx",
            ),
        ),
    ]
