apiVersion: apps/v1
kind: Deployment
metadata:
  name: light-messages-web
spec:
  selector:
    matchLabels:
      app: light-messages-web
  replicas: 1  # Changed to 1 for local development
  template:
    metadata:
      labels:
        app: light-messages-web  # This label must match the selector
    spec:
      containers:
        - name: backend-web
          # Repository and tag for the Docker image or local image
          image: abdelslam1997/light_messages_backend:v1.0.4
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "light_messages.settings.local"
          envFrom:
            - secretRef:
                name: backend-secret
            - secretRef:
                name: postgres-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: light-messages-channels
spec:
  selector:
    matchLabels:
      app: light-messages-channels
  replicas: 1  # Changed to 1 for local development
  template:
    metadata:
      labels:
        app: light-messages-channels  # This label must match the selector
    spec:
      containers:
        - name: backend-channels
          # Repository and tag for the Docker image or local image
          image: abdelslam1997/light_messages_backend:v1.0.4
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "light_messages.settings.local"
          envFrom:
            - secretRef:
                name: backend-secret
            - secretRef:
                name: postgres-secret
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: light-messages-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: light-messages.local
      http:
        paths:
          - path: /api/v1/
            pathType: Prefix
            backend:
              service:
                name: backend-service-web
                port:
                  number: 8000
          - path: /ws/
            pathType: Prefix
            backend:
              service:
                name: backend-service-channels
                port:
                  number: 8000