# Generated by Django 5.0.6 on 2024-12-14 07:39

import core_apps.users.utils.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lightmessagesuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core_apps.users.utils.images.get_profile_image_path,
                verbose_name="Profile Image",
            ),
        ),
    ]
