apiVersion: v1
kind: Service
metadata:
  name: backend-service-channels
  labels:
    app: light-messages-channels
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app: light-messages-channels