apiVersion: apps/v1
kind: Deployment
metadata:
  name: light-messages-web
  labels:
    app: light-messages-web
spec:
  replicas: 4
  selector:
    matchLabels:
      app: light-messages-web
  template:
    metadata:
      labels:
        app: light-messages-web
    spec:
      containers:
        - name: backend-web
          image: abdelslam1997/light_messages_backend:v1.0.2
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          # readinessProbe:
          #   httpGet:
          #     path: /api/v1/health/
          #     port: 8000
          #   initialDelaySeconds: 15
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /api/v1/health/
          #     port: 8000
          #   initialDelaySeconds: 15
          #   periodSeconds: 10
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "light_messages.settings.local"
            - name: POSTGRES_HOST
              value: "postgres-service"
            - name: POSTGRES_PORT
              value: "5432"
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: SERVICE_TYPE
              value: "web"